version: "3"

services:
  api:
    build: .
    container_name: kronter
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongo
    volumes:
      - ./potholefast/templates/:/app/templates/
    ports:
        - "7777:7777"

  mongo:
    image: mongo
    container_name: ${MONGO_HOST}
    restart: unless-stopped
    tty: true
    volumes:
      - /opt/tg_geo_db/mongo:/data/db
    ports:
      - "11943:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "7886:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:27017/
